version: "3.7"
services:
  db:
    image: mysql:8
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: gomail
      MYSQL_PASSWORD: gomail
      MYSQL_DATABASE: image_gomail
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      DB_HOST: tcp(db:3306)
    volumes:
      - ./docker/data:/docker-entrypoint-initdb.d
    networks:
      - backend

  # Api Service
  api:
    build:
      context: ./
      dockerfile: ./docker/build/golang/Dockerfile
    environment:
      CORS_ALLOWED_ORIGINS: "http://localhost:8000"
      API_PORT: "8080"
      MYSQL_USER: gomail
      MYSQL_PASSWORD: gomail
      MYSQL_DATABASE: image_gomail
      DB_HOST: tcp(db:3306)
    ports:
      - "8080:8080"
    volumes:
      - ./app:/go:rw
    networks:
      - backend

  redis:
    image: "redis:alpine"
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

networks:
  backend:
    driver: "bridge"